apiVersion: v2
name: superset
description: Apache Superset is a modern data exploration and visualization platform
type: application
version: 0.1.0
appVersion: "2.1.0"
keywords:
  - analytics
  - business intelligence
  - visualization
home: https://superset.apache.org/
sources:
  - https://github.com/apache/superset
maintainers:
  - name: fineken
    email: dzolotarev1980@gmail.com
