apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "superset.fullname" . }}
  labels:
    {{- include "superset.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "superset.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: {{ .Values.vault.role | quote }}
        vault.hashicorp.com/agent-inject-secret-superset: {{ .Values.vault.secretPath | quote }}
        vault.hashicorp.com/auth-path: {{ .Values.vault.authPath | quote }}
      {{- end }}
      labels:
        {{- include "superset.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "superset.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-db
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["superset-init"]
          env:
            - name: SUPERSET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "superset.fullname" . }}-vault
                  key: admin_username
            - name: SUPERSET_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ include "superset.fullname" . }}-vault
                  key: admin_email
            - name: SUPERSET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "superset.fullname" . }}-vault
                  key: admin_password
            - name: SUPERSET_FIRSTNAME
              value: {{ .Values.superset.init.adminUser.firstname }}
            - name: SUPERSET_LASTNAME
              value: {{ .Values.superset.init.adminUser.lastname }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8088
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
          env:
            - name: SUPERSET_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "superset.fullname" . }}-vault
                  key: secret_key
            - name: SUPERSET_MAPBOX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "superset.fullname" . }}-vault
                  key: mapbox_api_key
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "superset.fullname" . }}-vault
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "superset.fullname" . }}-vault
                  key: postgres_password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "superset.fullname" . }}-vault
                  key: redis_password
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
