apiVersion: v1
kind: Secret
metadata:
  name: {{ include "superset.fullname" . }}-secrets
  labels:
    {{- include "superset.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin_username: {{ .Values.superset.init.adminUser.username | quote }}
  admin_firstname: {{ .Values.superset.init.adminUser.firstname | quote }}
  admin_lastname: {{ .Values.superset.init.adminUser.lastname | quote }}
  admin_email: {{ .Values.superset.init.adminUser.email | quote }}
  admin_password: {{ .Values.superset.init.adminUser.password | quote }}
  secret_key: {{ .Values.superset.configOverrides.secret_key | quote }}
  mapbox_api_key: {{ .Values.superset.configOverrides.mapbox_api_key | quote }}
  postgres_user: {{ .Values.postgresql.postgresqlUsername | quote }}
  postgres_password: {{ .Values.postgresql.postgresqlPassword | quote }}
  redis_password: {{ .Values.redis.auth.password | quote }} 